"""Database lifecycle commands for local development and evaluation.

The application creates and incrementally migrates its small schema when a
repository is initialized. These commands provide a safe, repeatable wrapper
around that behavior and a deliberate full-data reset for a fresh test run.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import sqlite3
from pathlib import Path
from typing import Iterable

from app.core.config import BACKEND_DIR, get_settings
from app.evidence_pipeline.persistence.postgres import PostgresEvidenceRepository
from app.evidence_pipeline.persistence.sqlite import SQLiteEvidenceRepository


TABLES = (
    "investigation_observations",
    "investigation_sources",
    "verification_runs",
    "profiles",
    "observations",
    "raw_sources",
    "source_cache",
    "runs",
    "investigations",
)


def _is_postgres(database_url: str) -> bool:
    return database_url.startswith(("postgresql://", "postgres://"))


def _repository():
    settings = get_settings()
    if _is_postgres(settings.database_url):
        return PostgresEvidenceRepository(settings.database_url)
    return SQLiteEvidenceRepository(settings.database_url)


def migrate() -> None:
    """Create missing tables and apply the repository's in-place migrations."""
    _repository()
    print("Database schema is ready.")


def _clear_postgres(database_url: str) -> None:
    import psycopg

    # This is intentionally an explicit allow-list. It prevents an operator
    # command from accidentally truncating tables added outside this app.
    repository = PostgresEvidenceRepository(database_url)
    with repository._connect() as connection:
        with connection.cursor() as cursor:
            cursor.execute("TRUNCATE TABLE " + ", ".join(TABLES) + " CASCADE")


def _clear_sqlite(database_url: str) -> None:
    path = Path(database_url.removeprefix("sqlite:///"))
    repository = SQLiteEvidenceRepository(database_url)
    with repository._connect() as connection:
        for table in TABLES:
            connection.execute(f"DELETE FROM {table}")
        connection.execute("VACUUM")


def clear() -> None:
    """Delete all application records while keeping the schema."""
    settings = get_settings()
    if _is_postgres(settings.database_url):
        _clear_postgres(settings.database_url)
    else:
        _clear_sqlite(settings.database_url)
    print("All application database data was deleted; schema was preserved.")


def reset() -> None:
    """Clear all records, then initialize/migrate the schema again."""
    clear()
    migrate()
    print("Database reset complete. No investigations were seeded.")


def status() -> None:
    settings = get_settings()
    if _is_postgres(settings.database_url):
        repository = PostgresEvidenceRepository(settings.database_url)
        with repository._connect() as connection:
            with connection.cursor() as cursor:
                for table in reversed(TABLES):
                    cursor.execute(f"SELECT COUNT(*) FROM {table}")
                    print(f"{table}: {cursor.fetchone()[0]}")
    else:
        repository = SQLiteEvidenceRepository(settings.database_url)
        with repository._connect() as connection:
            for table in reversed(TABLES):
                count = connection.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
                print(f"{table}: {count}")


async def seed(path: str | None) -> None:
    """Seed investigations from a JSON list of PersonClues objects.

    Seeding is opt-in because the project does not have a canonical fixture
    dataset. The file may contain either clue objects or objects with a
    ``clues`` property; IDs are generated by the normal pipeline only, so this
    command is intended for future deterministic fixtures.
    """
    if not path:
        print("No seed file supplied. Use: make db-seed FILE=path/to/cases.json")
        return
    seed_path = Path(path)
    if not seed_path.exists():
        raise SystemExit(f"Seed file not found: {seed_path}")
    payload = json.loads(seed_path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise SystemExit("Seed file must contain a JSON list.")
    repository = _repository()
    for index, item in enumerate(payload, start=1):
        clues = item.get("clues", item) if isinstance(item, dict) else item
        if not isinstance(clues, dict) or not clues.get("name"):
            raise SystemExit(f"Seed item {index} must contain a clues.name value.")
        investigation_id = item.get("investigation_id") if isinstance(item, dict) else None
        if not investigation_id:
            investigation_id = f"seed_{index:04d}"
        await repository.create_investigation(
            investigation_id,
            json.dumps(clues, ensure_ascii=False),
            "1970-01-01T00:00:00+00:00",
        )
    print(f"Seeded {len(payload)} investigation input(s). Retrieval must be run separately.")


def clear_artifacts() -> None:
    artifacts = BACKEND_DIR / "artifacts"
    if not artifacts.exists():
        print("No local artifacts directory exists.")
        return
    for child in artifacts.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()
    print("Local run, verification, and evaluation artifacts were deleted.")


def main() -> None:
    parser = argparse.ArgumentParser(description="People Investigation database operations")
    parser.add_argument("command", choices=("migrate", "status", "clear", "reset", "seed", "clear-artifacts"))
    parser.add_argument("seed_file", nargs="?", help="JSON seed file for the seed command")
    args = parser.parse_args()
    if args.command == "migrate":
        migrate()
    elif args.command == "status":
        status()
    elif args.command == "clear":
        clear()
    elif args.command == "reset":
        reset()
    elif args.command == "seed":
        asyncio.run(seed(args.seed_file))
    else:
        clear_artifacts()


if __name__ == "__main__":
    main()
